### ISSUE TITLE
comparison with rrtools

### ISSUE THREAD

**Issue by jcolomb** [lwjohnst86/prodigenr#83]
https://github.com/benmarwick/rrtools
seem to be a quite similar project, is it?

**Comment by lwjohnst86** [comment]
Yes, I am aware of that project. I have a comment somewhere in my issues about looking over that package and maybe contacting the author. It is a very very similar project. They focus on writing papers (prodigenr has papers, slides, posters, abstracts) and their project template is different from this one (eg. they have `analysis/` folder while prodigenr has a structure similar to R packages, which I believe should be emulated since R package development is a well established and documented format).

**Comment by lwjohnst86** [comment]
And actually, they wrote an article about their idea and referenced prodigenr (which is a nice feeling hehe) and then created their package, so they are aware of prodigenr as well :)

**Comment by KristijanArmeni** [comment]
I've just learned about this one: https://drivendata.github.io/cookiecutter-data-science/ (opinionated and language agnostic project creator :) ). Perhaps to acknowledge under "related tools" at some later point.
